version: '3.9'

services:
  #Base de datos
  db:
    image: mysql:8.0.33
    container_name: mysqlServer
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dkf_egibide
      MYSQL_USER: grupo04
      MYSQL_PASSWORD: grupo04
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  #Backend
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: backend-egibide
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: dkf_egibide
      DB_USERNAME: grupo04
      DB_PASSWORD: grupo04
    ports:
      - '8000:80'
    depends_on:
      - db
    networks:
      - app-network

  #Frontend
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: frontend-egibide
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://backend:80
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
